name: .NET Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

   # - name: Setup .NET
   #   uses: actions/setup-dotnet@v3
      #with:
        #dotnet-version: '8.0.x'

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Publish
      run: dotnet publish -c Release -o publish

    - name: Deploy to IIS
      run: |
        # Put app offline (stops IIS app)
        New-Item "C:\inetpub\wwwroot\EFCoreApp\app_offline.htm" -ItemType File -Force

        Start-Sleep -Seconds 5

        # Delete old files
        Remove-Item "C:\inetpub\wwwroot\EFCoreApp\*" -Recurse -Force -ErrorAction SilentlyContinue

        # Copy new files
        Copy-Item "publish\*" "C:\inetpub\wwwroot\EFCoreApp" -Recurse -Force

        # Remove offline file (start app again)
        Remove-Item "C:\inetpub\wwwroot\EFCoreApp\app_offline.htm" -Force -ErrorAction SilentlyContinue

   # - name: Deploy to IIS
    #  run: |
       #  Remove-Item "C:\inetpub\wwwroot\EFCoreApp\*" -Recurse -Force
       #  Copy-Item "publish\*" "C:\inetpub\wwwroot\EFCoreApp" -Recurse

  #  - name: Recycle App Pool
      #run: |
         ##Restart-WebAppPool -Name "EFCoreApp"
