name: .NET Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

   # - name: Setup .NET
   #   uses: actions/setup-dotnet@v3
      #with:
        #dotnet-version: '8.0.x'

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Publish
      run: dotnet publish -c Release -o publish

    - name: Deploy to IIS
      run: |
         Remove-Item "C:\inetpub\wwwroot\EFCoreApp\*" -Recurse -Force
         Copy-Item "publish\*" "C:\inetpub\wwwroot\EFCoreApp" -Recurse

    - name: Recycle App Pool
      run: |
         Import-Module WebAdministration
         Restart-WebAppPool -Name "EFCoreApp"
